### ISSUE TITLE
项目的module中导入之后出现错误

### ISSUE THREAD

**Issue by ghost** [donkingliang/GroupedRecyclerViewAdapter#1]
错误:(40, 13) Failed to resolve: com.github.donkingliang:GroupedRecyclerViewAdapter:1.0.1
Show in File
Show in Project Structure dialog

这是什么原因呢？

**Comment by anonymouslh2** [comment]
好吧，我自己回答一下，找到原因了，我的project里没有导入 maven { url 'https://jitpack.io' }，只是在module里导入了，所有gradle同步失败。。。
