### ISSUE TITLE
请问怎样结合下拉刷新和上拉加载更多使用

### ISSUE THREAD

**Issue by nicelyjust** [donkingliang/GroupedRecyclerViewAdapter#10]
请问怎样结合下拉刷新和上拉加载更多使用

**Comment by donkingliang** [comment]
如果是使用了组头悬浮功能的话，就不能兼容下拉刷新的控件了。因为悬浮功能需要用StickyHeaderLayout嵌套RecyclerView，而大部分的下拉刷新控件也需要直接嵌套RecyclerView。
