### ISSUE TITLE
changeGroup刷新问题

### ISSUE THREAD

**Issue by super-hu** [donkingliang/GroupedRecyclerViewAdapter#11]
changeGroup的方法刷新一组数据是不是有问题。对于收缩状态->展开，countGroupItem计算值有误，getChildrenCount获取的收缩的值是0的，那最终通过notifyItemRangeChanged来刷新的item的数量是不正确的。

**Comment by donkingliang** [comment]
不要直接用RecyclerView.Adapter提供的列表刷新方法，而应该用GroupedRecyclerViewAdapter提供的刷新方法，这个我在介绍文档了提过了。还有组的展开和收起应该用insertChildren和removeChildren方法，这样就不会有计算错误的问题了，具体可以参考我在项目中提供的例子。谢谢！
