### ISSUE TITLE
使用 removeGroup(groupPosition);有问题

### ISSUE THREAD

**Issue by ootypoo** [donkingliang/GroupedRecyclerViewAdapter#14]
数据已经删除成功了，然后闪了一下，但是那条数据还在那显示，我下拉刷新一下才消失！

**Comment by donkingliang** [comment]
你是不是没有把你的数据从你自己的数据源里删除啊。removeGroup(groupPosition)的作用是通知数据变化并刷新列表。数据的删除是要你自己做的。把你对应的数据从你的数据列表中删除调就可以了。
