### ISSUE TITLE
数据一次性全都加在到了view上问题

### ISSUE THREAD

**Issue by lizhanqi** [donkingliang/GroupedRecyclerViewAdapter#15]
我在使用的过程中发现数据都是一次性直接加载完的,并不是根据滑动的时候进行加载的,这样首次初始化数据的时候很慢啊,这里您用viewHolder复用怎么复用的呢?

**Comment by donkingliang** [comment]
我在GroupedRecyclerViewAdapter内部有实现一个BaseViewHolder来复用item的。而且RecyclerView内部本身有自己的复用机制，如果我们的Adapter没有实现ViewHolder,列表根本就不会显示出来的。所以不用担心item无法复用的问题。
如果你的列表数据一次性直接加载完，有可能是因为其他原因造成的。比如RecyclerView被其他可滑动的Layout嵌套等，都可以会引起这个问题。
