### ISSUE TITLE
移动到指定头布局位置

### ISSUE THREAD

**Issue by yinge** [donkingliang/GroupedRecyclerViewAdapter#16]
有没有哪个方法 可以直接显示到指定的头布局位置。 比方说 我直接选择 让第4组显示在最上面

**Comment by donkingliang** [comment]
RecyclerView里有两个方法可以可以滚动到指定的item：
scrollToPosition(position);
smoothScrollToPosition(position);
这两个方法只有在填充了数据并且item没有显示在屏幕的情况下才有效。

你可以通过adapter.getPositionForGroupHeader(int groupPosition)来获取头部在RecyclerView的实际position。
