### ISSUE TITLE
吸顶和点击展开 一起使用 会有问题

### ISSUE THREAD

**Issue by mumu1071** [donkingliang/GroupedRecyclerViewAdapter#17]
![image](https://user-images.githubusercontent.com/14230058/43408427-f117c280-9453-11e8-8d25-70c8e701d042.png)
这种状态点击 ，位置数据错乱

**Comment by donkingliang** [comment]
是的，这是因为列表收起的时候，可能吸顶布局对应的item已经滑出屏幕引起的。
可以在列表收起的时候，加上下面的代码避免这种问题。
![image](https://user-images.githubusercontent.com/5499532/43431318-e2e9a5b0-949f-11e8-8cfd-0c1c4535eeed.png)

**Comment by mumu1071** [comment]
是的，可以了~
但是抖动问未有解决，比如说，上图中点击第七组展开，第七组header应该保持不动展开

**Comment by mumu1071** [comment]
还有一个建议，基类稍微设计过度，过千行代码，业务线的单个类，最多600行，否则需要分拆，当然，不是绝对。
面向接口编程，目的不是让其他人傻瓜用，那是工具类

**Comment by donkingliang** [comment]
我明白你的问题了，之前没有看明白你的问题，所以没有回复，现在回复，希望遇到同样问题的朋友能看到。
在列表收起的时候添加上面的代码，在列表展开的时候不用添加上面的代码。
if(){
//收起
//添加代码
} else{
//展开
}
应该是这样处理。

**Comment by lsqbeyond** [comment]
你好按照你的说法这样加的代码还是有问题，例如，都是展开的情况下，把第二组滑倒顶部，然后点击第二组的头部会把第一组展开，通过看toast，groupPoastion是0不是第二组的postion
 if (expandableAdapter.isExpand(groupPosition)) {
                    //收起
                    expandableAdapter.collapseGroup(groupPosition);

                    LinearLayoutManager linearLayoutManager = (LinearLayoutManager) rvList.getLayoutManager();
                    int firstVisibleItem = linearLayoutManager.findFirstVisibleItemPosition();
                    int stickyItem = adapter.getPositionForGroupHeader(groupPosition);
                    if(firstVisibleItem>=stickyItem){
                        rvList.scrollToPosition(stickyItem);
                    }
                } else {
                    expandableAdapter.expandGroup(groupPosition);
                }
望指教

**Comment by donkingliang** [comment]
你好，是因为我上个版本优化了点击监听回调的组下标计算，但是忘了修改吸顶项的点击下标计算，导致吸顶项的组下标一直返回0。现在我已经修复这个bug了。

**Comment by lsqbeyond** [comment]
您好刚刚重新下载新的工程，重新试了一下，又发现了1个问题：
之前的问题已经好了
问题1：每组都是展开的，例如：把第三组滑动到吸顶，然后点击第三组这时候第三组收起来了，但是第三组的位置不对有一半被隐藏了，越是点击后面的组被遮挡的越多，应该是哪里计算有问题

望请大佬指教

**Comment by donkingliang** [comment]
不是计算有问题，效果就是这样的。因为第3组头部吸顶时，其实第3组的item有可能是已经滑出屏幕的，这是把第3组收起，就是把第3组的子项移除，后面的组就很跟着顶上出，这是正常的。

**Comment by lsqbeyond** [comment]
谢谢你的及时回复，我看了下qq联系人分组确实是这效果。非常感谢



lsqbeyond@yeah.net
 
发件人： donkingliang
发送时间： 2019-11-29 14:33
收件人： donkingliang/GroupedRecyclerViewAdapter
抄送： lsq; Comment
主题： Re: [donkingliang/GroupedRecyclerViewAdapter] 吸顶和点击展开 一起使用 会有问题 (#17)
不是计算有问题，效果就是这样的。因为第3组头部吸顶时，其实第3组的item有可能是已经滑出屏幕的，这是把第3组收起，就是把第3组的子项移除，后面的组就很跟着顶上出，这是正常的。
