### ISSUE TITLE
列表点开吸顶后，刷新导致头部数据不会改变

### ISSUE THREAD

**Issue by Vince1221** [donkingliang/GroupedRecyclerViewAdapter#27]
麻烦你了

**Comment by donkingliang** [comment]
你好，你的意思是你使用头部吸顶列表，但是列表刷新，头部没有刷新，是吗？能具体表述一下你的问题，和提供一下你代码吗？

**Comment by Vince1221** [comment]
不好意思啊，因为某些原因不能提供代码，但能详细说一下：正确的说是点击了一下筛选功能后 列表头部不会马上更新 recyclerview要滚动一下才能刷新过来 孩子的数据却能及时更新




------------------ 原始邮件 ------------------
发件人: "donkingliang"<notifications@github.com>;
发送时间: 2019年3月5日(星期二) 下午4:35
收件人: "donkingliang/GroupedRecyclerViewAdapter"<GroupedRecyclerViewAdapter@noreply.github.com>;
抄送: "张文"<948719044@qq.com>; "Author"<author@noreply.github.com>; 
主题: Re: [donkingliang/GroupedRecyclerViewAdapter] 列表点开吸顶后，刷新导致头部数据不会改变 (#27)




你好，你的意思是你使用头部吸顶列表，但是列表刷新，头部没有刷新，是吗？能具体表述一下你的问题，和提供一下你代码吗？

**Comment by donkingliang** [comment]
你使用的版本是多少？刷新列表时调用的是哪个方法？

**Comment by Vince1221** [comment]
用的是最新的1.3.2，刷新调用  notifyDataChanged();

**Comment by Vince1221** [comment]
用的是最新版本的1.3.2，刷新调用notifyDataChanged();是在适配器里展开和收起方法里调用的




------------------ 原始邮件 ------------------
发件人: "donkingliang"<notifications@github.com>;
发送时间: 2019年3月5日(星期二) 下午4:50
收件人: "donkingliang/GroupedRecyclerViewAdapter"<GroupedRecyclerViewAdapter@noreply.github.com>;
抄送: "张文"<948719044@qq.com>; "Author"<author@noreply.github.com>; 
主题: Re: [donkingliang/GroupedRecyclerViewAdapter] 列表点开吸顶后，刷新导致头部数据不会改变 (#27)




你使用的版本是多少？刷新列表时调用的是哪个方法？

**Comment by donkingliang** [comment]
我这边测试不出这个问题。或者你把我github里的demo下载下来，按照你自己的功能修改一下，看有没有这个问题。

**Comment by Vince1221** [comment]
那，好的吧，如果再有问题我再问问你
