### ISSUE TITLE
removeAll方法无效

### ISSUE THREAD

**Issue by UltramanTIGA** [donkingliang/GroupedRecyclerViewAdapter#3]
adapter调用removeAll没有清空？

**Comment by donkingliang** [comment]
你是不是没有把列表的数据一起清空啊。removeAll方法提供的是数据的删除效果，跟RecyclerAdapter的notifyItemRangeRemoved方法是一样的。至于数据的变化是要你自己处理的。

**Comment by UltramanTIGA** [comment]
@donkingliang 是的，我清空列表数据就行了，我以为这个方法会帮我清除数据
