### ISSUE TITLE
无法设置setHasStableIds（trur）

### ISSUE THREAD

**Issue by 845479430** [donkingliang/GroupedRecyclerViewAdapter#33]
设置setHasStableIds（true）就报错Cannot change whether this adapter has stable IDs while the adapter has registered observers

**Comment by 845479430** [comment]
![image](https://user-images.githubusercontent.com/32659814/56630845-60123400-6685-11e9-84ea-778bd8594703.png)

**Comment by donkingliang** [comment]
因为GroupedRecyclerViewAdapter需要添加observer监听列表变化。而调用setHasStableIds方法的adapter不能有observer监听器，所以二者是冲突的。
