### ISSUE TITLE
notifyHeaderChanged(0)无效，刷新第一个标题无效

### ISSUE THREAD

**Issue by cnm7625904** [donkingliang/GroupedRecyclerViewAdapter#35]
使用此方法刷新第一个标题无效，数据不会改变，只有滑动影藏再次出现后数据才是正确的

**Comment by donkingliang** [comment]
经过我这边的测试是可以的。你可以试一下断点调试，看一下notifyHeaderChanged(0)最终调用的是不是notifyItemChanged(0)。

**Comment by cnm7625904** [comment]
![1558407317(1)](https://user-images.githubusercontent.com/19663248/58065076-03883300-7bb7-11e9-96e1-857d3cd93c4e.jpg)  感谢，这么快就回复了。进入了这个方法，我用的是1.3.2下载到本地使用的，我将数据清空，全部重新加载已经解决了我的问题，但是notifyHeaderChanged(0)无效，并且在adapter中第一个标题拿到的数据确实是正确的，但是显示的时候一直都显示最初的数据。
