### ISSUE TITLE
顶部布局缓存如何处理

### ISSUE THREAD

**Issue by love1314WOAINI** [donkingliang/GroupedRecyclerViewAdapter#37]
如果有显示隐藏布局的话，头部会出现问题

**Comment by love1314WOAINI** [comment]
![数据](https://user-images.githubusercontent.com/20281421/64663010-ef758380-d47c-11e9-932c-b65f9a906b66.jpg)

**Comment by donkingliang** [comment]
你在切换数据和隐藏、显示的时候有刷新列表吗？你显示/隐藏的是整个item还是item里的某个View。隐藏的方式是remove item还是 gone view?

**Comment by love1314WOAINI** [comment]
下面最右边的布局里有四个textview，分别同时显示里面的两个，由上面的“左右”控制显示哪两个，隐藏用的是gone，点击左右以后都调用了notifyDataChanged（），如果进入页面先点左右，就不会有第一个被隐藏，如果先点了上一月，然后再点击左右，就会出现第一个刚开始被隐藏的数据就会不显示，滑动的时候下面滑到Position==0的时候，应该就是顶部吸顶布局就不显示刚开始隐藏的那两个！我的怀疑是否viewholder缓存的时候gone没有缓存上？
谢谢大佬的回复

**Comment by donkingliang** [comment]
能否提供一下你的adapter的代码给我分析一下。你是否在onBindHeaderViewHolder里处理好View的显示和隐藏的复用。是只有吸顶顶item有问题还是所有的头部item都有问题？

**Comment by love1314WOAINI** [comment]
我在之前的基础上加了一个方法，传入一个值来判断隐藏 那两个textview
 public void setIsShowValue(boolean isValue) {
        this.isValue = isValue;
    }
这是BindHerderViewHolder相关的逻辑
 if (isValue) {
            holder.setVisible(R.id.item_huanbi_value, View.GONE);
            holder.setVisible(R.id.item_tongbi_value, View.GONE);
            holder.setVisible(R.id.item_detail_huanbi, View.VISIBLE);
            holder.setVisible(R.id.item_detail_tongbi, View.VISIBLE);
        } else {
            holder.setVisible(R.id.item_huanbi_value, View.VISIBLE);
            holder.setVisible(R.id.item_tongbi_value, View.VISIBLE);
            holder.setVisible(R.id.item_detail_huanbi, View.GONE);
            holder.setVisible(R.id.item_detail_tongbi, View.GONE);
        }
每次传入那个值的时候都刷新数据了，调用notifydataChanged()
只有吸顶的item有问题。只要下面的item滑动到吸顶的位置，也会隐藏，就是position == 0的位置才会隐藏，其他的不会有问题！
主要的问题是，我上面说的有时候他是会正常显示的，比如我先左右切换一下，然后我不管怎么切换数据他都是正常的，如果我先切换数据，那么刚开始被隐藏的那一块就会出现这种问题。
