### ISSUE TITLE
吸顶列表，当滑动列表2个组头到顶部的时候（且第一个组头高度划出屏幕一半的时候）然后更新列表数据，且更新数据源为空的时候，会很神奇！如图：

### ISSUE THREAD

**Issue by SanChunAndrroid** [donkingliang/GroupedRecyclerViewAdapter#38]
![0c8434699282b7c24958bdb4a9189bd](https://user-images.githubusercontent.com/45865597/66248414-11e77d80-e759-11e9-9e1c-2d4bdf888151.jpg
![341ca8417cc0469962ec12320ef2aaf](https://user-images.githubusercontent.com/45865597/66248418-2b88c500-e759-11e9-86cc-f78c6d07e83a.jpg)
)

**Comment by donkingliang** [comment]
你使用的最新的版本吗？这个问题在1.2.2版本只会应该是修复了的。

**Comment by SanChunAndrroid** [comment]
你确定吗，我是12天前下载你上面这个源码跑的哦，然后我就是自己加了个更新列表数据的操作导致这个问题的，难道你这上面的源码不是最新的吗？

**Comment by donkingliang** [comment]
是最新的。你这个bug是必现的吗？你能发一下你修改了什么吗？我在我的demo上清空数据或者替换数据都没有出现这种问题。

**Comment by SanChunAndrroid** [comment]
可能是我自己之前下的老版本误以为是新版本了吧，现在下这个demo运行又没问题了

**Comment by SanChunAndrroid** [comment]
我现在有个问题就是（同一个页面，有几个tab，有的tab页面是吸顶分组列表，有的tab页面是不分组列表，当在吸顶分组列表的时候，切换去不分组列表tab的时候也会报这个界面更新不过来的问题）

**Comment by SanChunAndrroid** [comment]
忘记说了（fragment+viewpager+tabLayout）组合
