### ISSUE TITLE
组头无法删除

### ISSUE THREAD

**Issue by Joker-Jun** [donkingliang/GroupedRecyclerViewAdapter#46]
//取到当前是哪一个组
                    int mCurrentGroups = adapter.getGroupPositionForPosition(position);
                    //取到当前在组中位置
                    int positionInGroup = adapter.getChildPositionForPosition(mCurrentGroups, position);
                    //执行删除某组中某个具体数据
                    dtoList.get(mCurrentGroups).getDatas().remove(positionInGroup);
                    //通知更新
                    adapter.notifyChildRemoved(mCurrentGroups, positionInGroup);
                    //商品数据全被移除时
                    ToastUtils.showShort("商品已删除" + "还剩下" +dtoList.get(mCurrentGroups).getDatas().size());
                    //仅剩组头
                    if (dtoList.get(mCurrentGroups).getDatas().size() == 0) {
                        adapter.notifyHeaderRemoved(mCurrentGroups);
                    }

仅剩组头的时候，无法删除，而是整个布局刷新了，但组头一直还在

**Comment by donkingliang** [comment]
你好，你这个问题是必现的吗？我这边测试没有遇到这种问题，如果你这边是必现的，希望你能提供一下demo和描述一下具体的情况，方便我排查问题。谢谢！

**Comment by Joker-Jun** [comment]
必现的哦
使用的recyclerview是：     implementation 'com.yanzhenjie.recyclerview:x:1.3.2'
使用的adapter 是：    implementation 'com.github.donkingliang:GroupedRecyclerViewAdapter:2.2.0'

侧滑删除的时候，就删用上面的删除，是OK的了
但是关于header的删除就都不成功

删除地方代码：

`    private void bingMenu(final SwipeRecyclerView recyclerView, final GwdGroupAdapter adapter, final List<GwdGoodsGroupsDto> dtoList) {
        // 创建菜单：
        SwipeMenuCreator mSwipeMenuCreator = new SwipeMenuCreator() {
            @Override
            public void onCreateMenu(SwipeMenu leftMenu, SwipeMenu rightMenu, int position) {
                // 根据ViewType来决定哪一个item该如何添加菜单。
                int viewType = adapter.judgeType(position);
                if (viewType == TYPE_CHILD) {
                    SwipeMenuItem deleteItem = new SwipeMenuItem(mRootView.getContext());
                    deleteItem.setBackgroundColor(mRootView.getContext().getColor(R.color.item_red))
                            .setText("删除")
                            .setTextColor(mRootView.getContext().getColor(R.color.white))
                            .setTextSize(15)
                            .setWidth(250)
                            .setHeight(ViewGroup.LayoutParams.MATCH_PARENT);
                    // 在Item右侧添加一个菜单。
                    rightMenu.addMenuItem(deleteItem);
                }
            }
        };

        OnItemMenuClickListener mItemMenuClickListener = new OnItemMenuClickListener() {
            @Override
            public void onItemClick(SwipeMenuBridge menuBridge, int position) {
                // 任何操作必须先关闭菜单，否则可能出现Item菜单打开状态错乱。
                ToastUtils.showShort("position " + position);
                menuBridge.closeMenu();

                // 左侧还是右侧菜单：
                int direction = menuBridge.getDirection();
                if (direction == RIGHT_DIRECTION) {
                    // 菜单在Item中的Position：
                    int menuPosition = menuBridge.getPosition();
                    //取到当前是哪一个组
                    int mCurrentGroups = adapter.getGroupPositionForPosition(position);
                    //取到当前在组中位置
                    int positionInGroup = adapter.getChildPositionForPosition(mCurrentGroups, position);
                    //执行删除某组中某个具体数据
                    dtoList.get(mCurrentGroups).getDatas().remove(positionInGroup);
                    //通知更新
                    adapter.notifyChildRemoved(mCurrentGroups, positionInGroup);
                    //商品数据全被移除时
/*                    ToastUtils.showLong("组" + mCurrentGroups + "的 第 " + positionInGroup
                            + "商品已删除" + ", 还剩下" + dtoList.get(mCurrentGroups).getDatas().size());*/
                    //仅剩标题
                    if (dtoList.get(mCurrentGroups).getDatas().size() == 0) {
                        ToastUtils.showLong("删除" + mCurrentGroups);
                        dtoList.remove(mCurrentGroups);
                        adapter.notifyHeaderRemoved(mCurrentGroups);
                    }
                }
            }
        };
        recyclerView.setOnItemMenuClickListener(mItemMenuClickListener);
        recyclerView.setSwipeMenuCreator(mSwipeMenuCreator);
        recyclerView.setItemAnimator(new FadeInLeftAnimator(new DecelerateInterpolator()));
    }`

数据源是

`public class GwdGoodsGroupsDto {

    /**
     * 组名类别
     */
    private int groupType;

    /**
     * 每组中具体数据，类型{@link GwdGoodsDto}
     */
    private List<GwdCarGoodsDto> datas;

    public GwdGoodsGroupsDto() {
    }

    public int getGroupType() {
        return groupType;
    }

    public void setGroupType(int groupType) {
        this.groupType = groupType;
    }

    public List<GwdCarGoodsDto> getDatas() {
        return datas;
    }

    public void setDatas(List<GwdCarGoodsDto> datas) {
        this.datas = datas;
    }

    @Override
    public String toString() {
        return "GwdGoodsGroupsDto{" +
                "groupType='" + groupType + '\'' +
                ", datas=" + datas +
                '}';
    }
}`

`public class GwdCarGoodsDto {

    /**
     * 类型：满减? 未开售？已失效
     */
    private int goodsType;

    private String goodsName;

    private String goodsContent;

    private int goodsCounts;

    private String goodsMaskContent;

    private boolean goodsIsChecked;

    private String goodsGroupTitle;
    private String goodsGroupContent;
    private String goodsGroupMore;

    public String getGoodsGroupTitle() {
        return goodsGroupTitle;
    }

    public void setGoodsGroupTitle(String goodsGroupTitle) {
        this.goodsGroupTitle = goodsGroupTitle;
    }

    public String getGoodsGroupContent() {
        return goodsGroupContent;
    }

    public void setGoodsGroupContent(String goodsGroupContent) {
        this.goodsGroupContent = goodsGroupContent;
    }

    public String getGoodsGroupMore() {
        return goodsGroupMore;
    }

    public void setGoodsGroupMore(String goodsGroupMore) {
        this.goodsGroupMore = goodsGroupMore;
    }

    public String getGoodsContent() {
        return goodsContent;
    }

    public void setGoodsContent(String goodsContent) {
        this.goodsContent = goodsContent;
    }

    public String getGoodsMaskContent() {
        return goodsMaskContent;
    }

    public void setGoodsMaskContent(String goodsMaskContent) {
        this.goodsMaskContent = goodsMaskContent;
    }

    public boolean isGoodsIsChecked() {
        return goodsIsChecked;
    }

    public void setGoodsIsChecked(boolean goodsIsChecked) {
        this.goodsIsChecked = goodsIsChecked;
    }

    public int getGoodsCounts() {
        return goodsCounts;
    }

    public void setGoodsCounts(int goodsCounts) {
        this.goodsCounts = goodsCounts;
    }

    public String getGoodsTypeContent() {
        return goodsContent;
    }

    public void setGoodsTypeContent(String goodsTypeContent) {
        this.goodsContent = goodsTypeContent;
    }

    public int getGoodsType() {
        return goodsType;
    }

    public void setGoodsType(int goodsType) {
        this.goodsType = goodsType;
    }

    public String getGoodsName() {
        return goodsName;
    }

    public void setGoodsName(String goodsName) {
        this.goodsName = goodsName;
    }

    @Override
    public String toString() {
        return "GwdCarGoodsDto{" +
                "goodsType=" + goodsType +
                ", goodsName='" + goodsName + '\'' +
                ", goodsContent='" + goodsContent + '\'' +
                ", goodsCounts=" + goodsCounts +
                ", goodsMaskContent='" + goodsMaskContent + '\'' +
                ", goodsIsChecked=" + goodsIsChecked +
                ", goodsGroupTitle='" + goodsGroupTitle + '\'' +
                ", goodsGroupContent='" + goodsGroupContent + '\'' +
                ", goodsGroupMore='" + goodsGroupMore + '\'' +
                '}';
    }`
