### ISSUE TITLE
吸顶列表刷新数据后第一组组头刷新会有问题（仅第一组表头）

### ISSUE THREAD

**Issue by liuguangxu1988** [donkingliang/GroupedRecyclerViewAdapter#51]
吸顶列表StickyHeaderLayout包裹RecyclerView
时间排序第一组组头 2020-05-23
从时间排序切换到字母排序后
列表第一组组头显示A正确，这时上滑列表把第一组组头划出屏幕外再向下划回来
第一组组头由正确的A变回了原来的2020-05-23
其他组头和child都无异常，只是第一组吸顶组头BUG
版本2.3.0  切换后数据正常 已调用notifyDataChanged()
希望大神有空排查下这个问题

**Comment by donkingliang** [comment]
你好，这个问题是必现的还是概率性的？我这边没有重现到。你能提供一下你的adapter的代码让我排查一下吗？

**Comment by liuguangxu1988** [comment]
你好 是必现的 基本逻辑很简单

public class WordBookAdapter extends GroupedRecyclerViewAdapter {
    private Context mContext;
    protected ArrayList<WordBookGroup> mGroups;
    private PopupWindow popupWindow;
    public WordBookAdapter(Context context, ArrayList<WordBookGroup> groups) {
        super(context);
        mContext = context;
        mGroups = groups;
    }

    @Override
    public int getGroupCount() {
        return mGroups == null ? 0 : mGroups.size();
    }

    @Override
    public int getChildrenCount(int groupPosition) {
        ArrayList<BookItem> children = mGroups.get(groupPosition).getWordBookChild();
        return children == null ? 0 : children.size();
    }

    public void clear() {
        mGroups.clear();
        notifyDataChanged();
    }

    public void setGroups(ArrayList<WordBookGroup> groups) {
        mGroups = groups;
        notifyDataChanged();
    }

    @Override
    public boolean hasHeader(int groupPosition) {
        return true;
    }

    @Override
    public boolean hasFooter(int groupPosition) {
        return false;
    }

    @Override
    public int getHeaderLayout(int viewType) {
        return R.layout.item_wordbook_header;
    }

    @Override
    public int getFooterLayout(int viewType) {
        return R.layout.item_wordbook_header;
    }

    @Override
    public int getChildLayout(int viewType) {
        return R.layout.item_wordbook;
    }

    @Override
    public void onBindHeaderViewHolder(BaseViewHolder holder, int groupPosition) {
        WordBookGroup entity = mGroups.get(groupPosition);
        holder.setText(R.id.tvWordBookHeader, entity.getHeader());
        holder.setText(R.id.tvHeaderCount,"("+mGroups.get(groupPosition).getWordBookChild().size()+"词)");
    }

    @Override
    public void onBindFooterViewHolder(BaseViewHolder holder, int groupPosition) {

    }

    @Override
    public void onBindChildViewHolder(final BaseViewHolder holder, final int groupPosition, final int childPosition) {
        BookItem entity = mGroups.get(groupPosition).getWordBookChild().get(childPosition);
        holder.setText(R.id.tvWord, entity.getSpell());
        holder.setText(R.id.tvPhonetic, entity.getUs_phonetic());
    }
}

**Comment by donkingliang** [comment]
我用你的代码也没有重现到。你可以试一下用github上的例子，换成你的数据和adapter，看能不能重现。
