### ISSUE TITLE
下拉加载头部重复问题

### ISSUE THREAD

**Issue by octopusy** [donkingliang/GroupedRecyclerViewAdapter#53]
以月份分组为例，假如4月有60条数据，每次请求后台加载20条，下拉一次，拼装一次数据，这样的话，就会生成3个4月的重复头部了，请问这个有什么好的解决方案吗？

![image](https://user-images.githubusercontent.com/8248053/83757440-132fc800-a6a3-11ea-9293-1c9b46d3b252.png)

![image](https://user-images.githubusercontent.com/8248053/83757500-280c5b80-a6a3-11ea-8501-02e09749e58a.png)

![image](https://user-images.githubusercontent.com/8248053/83757582-45d9c080-a6a3-11ea-947e-0f02e8871cb6.png)

**Comment by octopusy** [comment]
同一个分组下面，下拉加载数据，会生成多组重复的头部，有办法能解决这个问题吗？

**Comment by donkingliang** [comment]
你应该把同组的数据放在组的子列表里，而不是没有加载都建一个分组
