### ISSUE TITLE
请问动态刷新头部item的某个值要怎么写？

### ISSUE THREAD

**Issue by Sunhulg** [donkingliang/GroupedRecyclerViewAdapter#54]
头部item有一个用户头像，要通过API循环去获取用户的头像 然后再更新在列表上，请问要怎么写或者调用哪个方法？

**Comment by donkingliang** [comment]
先设置你头部的数据，然后调用notifyHeaderChanged刷新头部

**Comment by Sunhulg** [comment]
> 先设置你头部的数据，然后调用notifyHeaderChanged刷新头部

感谢，已实现
