### ISSUE TITLE
吸顶的viewholder是recyclerview写的多个tab，选中态无法同步以及滑动位置无法一致问题

### ISSUE THREAD

**Issue by galaxylei** [donkingliang/GroupedRecyclerViewAdapter#55]
不知道有没有遇到过吸顶的viewholder是用recyclerview写的另一个复杂UI，状态无法统一的问题应该怎解？

**Comment by donkingliang** [comment]
你的意思是吸顶的view和列表中的头部是不一样的吗？如果是这样就不能实现，因为这个库的吸顶就是通过复用列表中的头部实现的。
