### ISSUE TITLE
kotlin获取不到databinding

### ISSUE THREAD

**Issue by moo611** [donkingliang/GroupedRecyclerViewAdapter#56]

**Comment by donkingliang** [comment]
是因为kotlin和databinding的冲突问题吗？试一下这个
https://blog.csdn.net/EthanCo/article/details/54693140?utm_medium=distribute.pc_relevant_t0.none-task-blog-BlogCommendFromMachineLearnPai2-1.compare&depth_1-utm_source=distribute.pc_relevant_t0.none-task-blog-BlogCommendFromMachineLearnPai2-1.compare
