### ISSUE TITLE
有个问题想请教一下 

### ISSUE THREAD

**Issue by yuanchenghao** [donkingliang/GroupedRecyclerViewAdapter#6]
您好，我现在的需求是这样的  图片传不上去  gridview item如果是奇数个 最后一个item跨行显示 但是gridlayout只能跨列显示 不知道该怎么搞 想问一下该怎么弄

**Comment by yuanchenghao** [comment]
![default](https://user-images.githubusercontent.com/15939940/33160151-c41012ce-d054-11e7-87c8-69d0da4336f8.png)

**Comment by donkingliang** [comment]
我没看懂你描述的问题是什么？你能详细描述一下你的问题吗？或者你也可以加我QQ一起讨论一下。谢谢！

**Comment by yuanchenghao** [comment]
嗯 188897876
