### ISSUE TITLE
实现只有组头布局，怎么实现复杂的子布局？

### ISSUE THREAD

**Issue by lutao2599** [donkingliang/GroupedRecyclerViewAdapter#60]
您好，使用了您的方法实现了只有组头的列表，但是子布局想要实现多布局，该怎么做呢？继承了您的控件就不能继承其他的了

**Comment by donkingliang** [comment]
复写getChildViewType方法，根据groupPosition和childPosition返回不同的type类型，然后在getChildLayout根据不同的类型返回不同的布局。其实就跟普通的adapter实现多类型item是一样的，只不过是复写的方法不同而已。

你可以看我demo中的VariousAdapter，实现了不同类型的头部、尾部和子view。

**Comment by lutao2599** [comment]
好的，非常感谢您的耐心解答!




------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "donkingliang/GroupedRecyclerViewAdapter"                                                                                    <notifications@github.com&gt;;
发送时间:&nbsp;2020年11月27日(星期五) 晚上6:04
收件人:&nbsp;"donkingliang/GroupedRecyclerViewAdapter"<GroupedRecyclerViewAdapter@noreply.github.com&gt;;
抄送:&nbsp;"追梦赤子"<1336440850@qq.com&gt;;"Author"<author@noreply.github.com&gt;;
主题:&nbsp;Re: [donkingliang/GroupedRecyclerViewAdapter] 实现只有组头布局，怎么实现复杂的子布局？ (#60)





 
复写getChildViewType方法，根据groupPosition和childPosition返回不同的type类型，然后在getChildLayout根据不同的类型返回不同的布局。其实就跟普通的adapter实现多类型item是一样的，只不过是复写的方法不同而已。
 
你可以看我demo中的VariousAdapter，实现了不同类型的头部、尾部和子view。
