### ISSUE TITLE
用了另外一个项目额外添加header问题

### ISSUE THREAD

**Issue by lutao2599** [donkingliang/GroupedRecyclerViewAdapter#63]
您好，请问额外添加header后，使用recyclerview快速定位到指定位置时组头不能到顶部，请问该怎么解决？

**Comment by donkingliang** [comment]
我猜测是你添加header后，item的position变化了，所以你定位时传的position不是你实际需要的位置，你试一下重新计算定位的position。

**Comment by lutao2599** [comment]
感谢



------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "donkingliang/GroupedRecyclerViewAdapter"                                                                                    <notifications@github.com&gt;;
发送时间:&nbsp;2020年12月2日(星期三) 下午4:36
收件人:&nbsp;"donkingliang/GroupedRecyclerViewAdapter"<GroupedRecyclerViewAdapter@noreply.github.com&gt;;
抄送:&nbsp;"追梦赤子"<1336440850@qq.com&gt;;"Author"<author@noreply.github.com&gt;;
主题:&nbsp;Re: [donkingliang/GroupedRecyclerViewAdapter] 用了另外一个项目额外添加header问题 (#63)





 
我猜测是你添加header后，item的position变化了，所以你定位时传的position不是你实际需要的位置，你试一下重新计算定位的position。

**Comment by lutao2599** [comment]
麻烦问下，怎么重新计算position位置？没找到合适的方法



------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "donkingliang/GroupedRecyclerViewAdapter"                                                                                    <notifications@github.com&gt;;
发送时间:&nbsp;2020年12月2日(星期三) 下午4:36
收件人:&nbsp;"donkingliang/GroupedRecyclerViewAdapter"<GroupedRecyclerViewAdapter@noreply.github.com&gt;;
抄送:&nbsp;"追梦赤子"<1336440850@qq.com&gt;;"Author"<author@noreply.github.com&gt;;
主题:&nbsp;Re: [donkingliang/GroupedRecyclerViewAdapter] 用了另外一个项目额外添加header问题 (#63)





 
我猜测是你添加header后，item的position变化了，所以你定位时传的position不是你实际需要的位置，你试一下重新计算定位的position。

**Comment by donkingliang** [comment]
一般如果是由于添加header导致的position改变，那么item的实际position应该等于position+header的数量。

使用holder.getLayoutPosition()可以获取到item的实际position，你可以跟你定位时传的position对比一下。

**Comment by lutao2599** [comment]
谢谢



------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "donkingliang/GroupedRecyclerViewAdapter"                                                                                    <notifications@github.com&gt;;
发送时间:&nbsp;2020年12月2日(星期三) 下午4:49
收件人:&nbsp;"donkingliang/GroupedRecyclerViewAdapter"<GroupedRecyclerViewAdapter@noreply.github.com&gt;;
抄送:&nbsp;"追梦赤子"<1336440850@qq.com&gt;;"Author"<author@noreply.github.com&gt;;
主题:&nbsp;Re: [donkingliang/GroupedRecyclerViewAdapter] 用了另外一个项目额外添加header问题 (#63)





 
一般如果是由于添加header导致的position改变，那么item的实际position应该等于position+header的数量。
 
使用holder.getLayoutPosition()可以获取到item的实际position，你可以跟你定位时传的position对比一下。
