### ISSUE TITLE
子项点击事件无法找到控件id

### ISSUE THREAD

**Issue by zhushenwudi** [donkingliang/GroupedRecyclerViewAdapter#64]
recyclerViewInputAdapter.setOnChildClickListener((adapter, holder, groupPosition, childPosition) -> {
     if (holder.itemView.getId() == R.id.xxx) {
           // 这里找不到控件id，前者为-1
           // 是不是应该回传一个view
     }
}

**Comment by donkingliang** [comment]
你怎么去获取itemview的id，如果你想获取item中的某个view,应该使用holder.itemView.get(id)，如果你想获取itemview的id，应该给item的根布局设置个id，没有设置id的view都是-1的。
