### ISSUE TITLE
changeDataSet()后holder.get(R.id.xxx)返回null

### ISSUE THREAD

**Issue by SunshineNumber1** [donkingliang/GroupedRecyclerViewAdapter#7]
刷新数据时调用changeDataSet();在onBindHeaderViewHolder(BaseViewHolder holder, int groupPosition)中holder.get(R.id.xxx);一直返回null

**Comment by SunshineNumber1** [comment]
作者大大有没有 联系方式，或是交流群阿 ，项目急急急

**Comment by donkingliang** [comment]
你看一下你设置给adapter的布局是不是没有那个对应的id啊。

我的资料里有我的QQ。

**Comment by SunshineNumber1** [comment]
谢谢 作者大大 耐心指导 调试，解决问题。

**Comment by wxy13382050875** [comment]
大神，你好，进入页面首次刷新是正常的，但下拉刷新后会闪退，看原因是holder.get(R.id.xxx); 反回null 请问这个是什么原因
