### ISSUE TITLE
折叠的例子中，第一行header右边的箭头，在打开收起时不会变

### ISSUE THREAD

**Issue by simdm** [donkingliang/GroupedRecyclerViewAdapter#8]

**Comment by donkingliang** [comment]
我测试是可以的啊

**Comment by simdm** [comment]
我知道了，我修改了xml，增加了锁定header的功能，xml增加了com.donkingliang.groupedadapter.widget.StickyHeaderLayout
这时出现这个问题。

**Comment by simdm** [comment]
能解决这个问题么？

**Comment by donkingliang** [comment]
多谢你给我反馈这个问题。我大概知道是什么原因了。这个bug需要更新个版本才能解决。如果你用现在这个版本，要想解决这个问题的话，你可以在列表展开或收起之后，通过反射调用StickyHeaderLayout的updateStickyView()方法刷新悬浮布局。updateStickyView()是私有的，需要通过反射调用。

**Comment by simdm** [comment]
好的，明白了，多谢了
